language: python

branches:
  except:
    - gh-pages

cache:
  directories:
    - "${HOME}/.pip"

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy


matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox
  - "find ${HOME}/.pip -name log -o -name __pycache__ -type d | xargs -I {} rm -rf {}"

after_success:
  - pylint company
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: steenzout
  password:
    secure: todo
  on:
    tags: true
