language: python
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
  allow_failures:
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install tox

before_script:
  - mkdir -p log

script:
  - tox

after_script:
  - rm -rf log

after_success:
  - pylint company
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: steenzout
  password:
    secure: todo
  on:
    tags: true
